using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using MvvmHelpers;
using System.Text;

namespace PetInsights_all.Model
{
    public class Pet : BaseViewModel
    {

        private static string NotKnown = "Not Known";  // move to strings.xml for localization

        // NOTE - all members that have a _VarName = NotKnown are optional

        public string PetId { get; set; } // unique id generated by firebase
        public string PetType { get; set; } //i.e dog, cat, hamster, bird, reptile
        public string ImgIcon { get; set; } // first image uploaded + used on pet list view
        public string Name { get; set; } // name of the pet
        public int Age { get; set; }    // specific number if provided
        public string AgeRange { get; set; } // i.e. 6m-1y, 1-2y (find the formatting that's more readable)
        public string Sex { get; set; } // Male, Female, Unknown
        public string Address { get; set; } // city or zip
        public string Affiliation { get; set; } // default to the org's or fosters name
      //  public List<string> Media { get; set; } // so far includes image urls
      //  public List<string> Comments { get; set; }

        
        private ObservableCollection<string> _media = new ObservableCollection<string>();

        public ObservableCollection<string> Media
        {
            get { return _media; }
            set
            {
                _media = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _comments = new ObservableCollection<string>();

        public ObservableCollection<string> Comments
        {
            get { return _comments; }
            set
            {
                _comments = value;
                OnPropertyChanged();
            }
        }
        

        private string _Hypoallergenic = NotKnown; // base this value off of the breed
        public string Hypoallergenic
        {
            get
            {
                return _Hypoallergenic;
            }
            set
            {
                _Hypoallergenic = value;
            }
        }

        private string _Sheds = NotKnown; // base this value off of the breed
        public string Sheds
        {
            get
            {
                return _Sheds;
            }
            set
            {
                _Sheds = value;
            }
        }

        private string _Breed = NotKnown;    //Make Default "Not Known", only overwrite if we know
        public string Breed
        {
            get
            {
                return _Breed;
            }
            set
            {
                _Breed = value;
            }
        }

        private string _MedicalCondition = NotKnown; // Yes, No, Not Known, default to Not Known
        public string MedicalCondition
        {
            get
            {
                return _MedicalCondition;
            }
            set
            {
                _MedicalCondition = value;
            }
        }

        private string _MedicalConditionDetails = NotKnown; // describe the medical condition if true
        public string MedicalConditionDetails
        {
            get
            {
                return _MedicalConditionDetails;
            }
            set
            {
                _MedicalConditionDetails = value;
            }
        }

        private string _Size = NotKnown; // small, medium, big, default to "Not Known"
        public string Size
        {
            get
            {
                return _Size;
            }
            set
            {
                _Size = value;
            }
        }

        public List<string> Personality { get; set; } // collection of the following: Energetic, Friendly to children, Friendly to other pets, Calm, protective, Traumatized, Cuddly, Nervous, Reactive
                                                      // if List Count == 0, don't display

        private string _Trained = NotKnown; // Yes, No, Not Known  -- unclear on what kind of training we're talking about though
        public string Trained
        {
            get
            {
                return _Trained;
            }
            set
            {
                _Trained = value;
            }
        }

        private string _PottyTrained = NotKnown; // Yes, No, Not Known 
        public string PottyTrained
        {
            get
            {
                return _PottyTrained;
            }
            set
            {
                _PottyTrained = value;
            }
        }


        private string _Maintenance = NotKnown; // High, Low, Moderate (like if it required frequent vet visits i.e. some breeds need eye drops, some breeds need their ear hair plucked, etc.
        public string Maintenance
        {
            get
            {
                return _Maintenance;
            }
            set
            {
                _Maintenance = value;
            }
        }

        private string _ApartmentFriendly = NotKnown;
        public string ApartmentFriendly
        {
            get
            {
                return _ApartmentFriendly;
            }
            set
            {
                _ApartmentFriendly = value;
            }
        }

    }
}
